FROM ruby:2.4.4

RUN apt-get update -qq && \
  apt-get install -y \
  build-essential \
  git \
  libgmp3-dev \
  libpq-dev \
  libsqlite3-dev \
  wkhtmltopdf \
  postgresql-client

WORKDIR /usr/src/app

COPY ./roadmap/Gemfile* ./

RUN bundle install --without mysql

VOLUME /usr/src/app

EXPOSE 3000

CMD bundle install --without mysql; rake db:migrate; bundle exec puma -C config/puma.rb
